services:
  app-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:7860"
    environment:
      - HOST=0.0.0.0
      - PORT=7860
    volumes:
      - ./models:/app/models

  locust-service:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    depends_on:
      - app-service
    environment:
      - LOCUST_HOST=http://app-service:7860